services:
  air-venture-db:
    container_name: air-venture-db
    image: mysql:8.0
    platform: linux/arm64
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - air-venture-db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airventure-app
    platform: linux/arm64
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - air-venture-db
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      - JAVA_OPTS=-XX:+UseSerialGC -XX:-UseCompressedOops -XX:UseSVE=0 # Options de performance Java

volumes:
  air-venture-db:
