name: Build and deploy

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:air_venture_test
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: test  # Activation du profil de test

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configuration de Java 17
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'  # Garde Java 17

      # Étape 3 : Exécution des tests unitaires avec H2
      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      # Étape 4 : Construction de l'application
      - name: Build application
        run: mvn -B package --file pom.xml

      # Étape 5 : Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 6 : Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 7 : Build et push de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/air_venture_back:latest
