name: Build and deploy

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables from .env
        uses: c-py/action-dotenv-to-setenv@v5
        with:
          env-file: .env
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/air_venture_back:latest
